/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */
 
 description = """
 Example Gradle project demostrating The Gradle for java application
 Project name: ${project.name}
 """
 
 plugins{
     //Apply the applicationj plugin for build java application
	 application
  }
  
  repositories{
     //Use maven
	 mavenCentral()
  }
  
  dependencies{
      //Specify test NG
	  testImplementation("org.testng:testng:7.4.0")
	  
	  //The dependency also uses the google guva library
	  implementation("com.google.guava:guava:30.0-jre")
  }
  
  application{
     //Defin application
	 mainClass.set("GradleDemo.GradleDemo")
  
  }
  
  tasks.test{
     //Use TestNG
	 useTestNG()
   }
 
 
 
 
